name: Build
on:
  push:
    branches:
      - main
jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@master
        with:
          ref: main
      - name: Prepare environment
        run: |
          mkdir -p ./out
      - name: Run pdflatex prebiber on main
        uses: dante-ev/latex-action@latest
        with:
          root_file: main.tex
          compiler: pdflatex
          args: -interaction=nonstopmode -output-directory=./out -shell-escape
      - name: Run biber
        uses: dante-ev/latex-action@latest
        with:
          root_file: main.bcf
          compiler: biber
          args: --input-directory=./out --output-directory=./out
      - name: Run pdflatex on main
        uses: dante-ev/latex-action@latest
        with:
          root_file: main.tex
          compiler: pdflatex
          args: -interaction=nonstopmode -output-directory=./out main.tex -shell-escape
      - name: Upload pdf to workflow final
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: Final_built
          path: out
      - name: Copy built pdf
        run: |
          mkdir compiled
          cp ./out/main.pdf ./compiled/main.pdf
      - name: Push on master branch
        uses: github-actions-x/commit@v2.8
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          push-branch: 'master'
          commit-message: 'publish built pdf to master [skip ci]'
          force-add: 'true'
          files: compiled/main.pdf
          name: Stefano Moia
          email: s.moia.research@gmail.com
